# Generated by Django 2.2.11 on 2020-04-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('name', models.TextField(default='')),
                ('interest', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.TextField()),
                ('notes', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
