# Generated by Django 2.2.11 on 2020-04-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
