# Generated by Django 2.2.11 on 2020-04-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TextField()),
                ('taken', models.BooleanField(default=False)),
                ('appointment_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tours.Tours')),
            ],
        ),
    ]
