# Generated by Django 2.2.11 on 2020-03-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='times',
            field=models.TextField(),
        ),
    ]
