# Generated by Django 2.2.11 on 2020-03-31 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        ('times', '0002_auto_20200330_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='times',
            old_name='times',
            new_name='time',
        ),
        migrations.AddField(
            model_name='times',
            name='appointment_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.DO_NOTHING, to='tours.Tours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='times',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
