# Generated by Django 2.2.11 on 2020-04-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0003_auto_20200331_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='appointment_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tours.Tours'),
        ),
    ]
